# Pandas Practice

This notebook is dedicated to practicing different tasks with pandas. The solutions are available in a solutions notebook, however, you should always try to figure them out yourself first.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further references and resources, it's advised to check out the [pandas documentation](https://pandas.pydata.org/pandas-docs/stable/).

In [2]:
# Import pandas
import pandas as pd

In [3]:
# Create a Series of three different colours
colours = pd.Series(['Red', 'Blue', 'Yellow'])

In [4]:
# View the Series of different colours
colours

0       Red
1      Blue
2    Yellow
dtype: object

In [5]:
# Create a Series of three different car types and view it
car_types = pd.Series(["Toyota", "BMW", "Nissan"])
car_types

0    Toyota
1       BMW
2    Nissan
dtype: object

In [6]:
# Combine the Series of cars and colours into a DataFrame
df = pd.DataFrame(
  {
    'Car Type': car_types,
    'Colour': colours
	}
)
df

  Car Type  Colour
0   Toyota     Red
1      BMW    Blue
2   Nissan  Yellow

In [7]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv('../../data/assignments/car-sales.csv')
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

**Note:** Since you've imported `car-sales.csv` as a DataFrame, we'll now refer to this DataFrame as 'the car sales DataFrame'.

In [8]:
# Export the DataFrame you created to a .csv file
from pathlib import Path

In [9]:
filepath = Path('../../data/assignments/car-sales-export.csv')
filepath.parent.mkdir(parents=True, exist_ok=True)
df.to_csv(filepath)

In [10]:
# Find the different data types of the car sales DataFrame
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price            object
dtype: object

In [11]:
# Describe your current car sales DataFrame using describe()
car_sales.describe().T

,count,mean,std,min,25%,50%,75%,max
Odometer (KM),10.0,78601.4,61983.471735,11179.0,35836.25,57369.0,96384.5,213095.0
Doors,10.0,4.0,0.471405,3.0,4.00,4.0,4.0,5.0

In [12]:
# Get information about your car sales DataFrame using info()
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Colour         10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

What does it show you?

In [36]:
# Create a Series of different numbers and find the mean of them
numbers = [8, 14, 35, 97, 56, 28, 5, 41, 73, 4]
series_mean = pd.Series(numbers)
print(f"Mean: {series_mean.mean()}")

Mean: 36.1

In [37]:
# Create a Series of different numbers and find the sum of them
series_sum = pd.Series(numbers)
print(f"Sum: {series_sum.sum()}")

Sum: 361

In [38]:
# List out all the column names of the car sales DataFrame
columns = car_sales.columns.to_list()
print("--- DataFrame Column Names: ---")
for column in columns:
  print(column)

--- DataFrame Column Names: ---
Make
Colour
Odometer (KM)
Doors
Price

In [35]:
# Find the length of the car sales DataFrame
shape = car_sales.shape
length = shape[0]
print(f"Length of DataFrame: {length}")

Length of DataFrame: 10

In [33]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head(5)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [34]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00

In [39]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail(5)

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [40]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object

In [43]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Make                    BMW
Colour                Black
Odometer (KM)         11179
Doors                     5
Price            $22,000.00
Name: 3, dtype: object